name: Laravel

on:
  push:
    branches: [ "complete" ]
  pull_request:
    branches: [ "complete" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Migrate
      run: php ./artisan migrate
